### ISSUE TITLE
Unable to use Number-Matching MFA with SSH

### ISSUE THREAD

**Issue by deejay-ursys** [himmelblau-idm/himmelblau#162]
When attempting to SSH authenticate to a system with an account that uses Microsoft Authenticator (Push) MFA with Number-Matching enabled, the prompt showing what number to enter is not properly sent to the user.

When attempting to log in locally (eg: `su -l user@domain.onmicrosoft.com`), the password prompt and MFA code display as expected.
When logging in remotely via SSH (eg: `ssh user@domain.onmicrosoft.com@dev01`), only the password prompt is shown immediately, the MFA code is not shown until the authentication is failed and a new InteractivePasswordPrompt is shown.

My assumption is this is related to, or caused by, this bug where PAM info messages are not flushed to console until interaction is required, [OpenSSH Bugzilla 2876](https://bugzilla.mindrot.org/show_bug.cgi?id=2876).

```bash
## Local Login
admin@dev01:~$ su -l user@domain.onmicrosoft.com
Password:
Open your Authenticator app, and enter the number '73' to sign in.
## Note: I get the MFA push notification here and am able to complete it
user@domain.onmicrosoft.com@dev01:~$ whoami
user@domain.onmicrosoft.com
user@domain.onmicrosoft.com@dev01:~$

## SSH Login
localuser@workstation:~$ ssh user@domain.onmicrosoft.com@dev01
(user@domain.onmicrosoft.com@dev01) Password:
## Note: I get the MFA push notification here, I am unable to complete it as I have no code, so it gets denied
(user@domain.onmicrosoft.com@dev01) Open your Authenticator app, and enter the number '59' to sign in.
Password: ^C
localuser@workstation:~$
```

**Comment by dmulder** [comment]
This could be an ssh configuration issue. The defaults are a bit different for each distro.

**Comment by dmulder** [comment]
For one, I recall you need the `keyboard-interactive` option assigned in `AuthenticationMethods`.

**Comment by dmulder** [comment]
I think these options in your sshd_config should do it:
```
AuthenticationMethods keyboard-interactive:pam
KbdInteractiveAuthentication yes
UsePAM yes
```
Seems like not all of these were required for me. You'll have to tinker with the configuration a bit.

**Comment by deejay-ursys** [comment]
I've tested the sshd_config options you've provided, as well as tinkering with other related sshd_config options.
I am still unable to get the number-matching code to appear immediately after entering the password during ssh authentication.

The system I am testing on is an Ubuntu 22.04 LTS server.
I have tested both the stock Ubuntu `sshd_config` as well as a transplanted `sshd_config` file from the OpenSuse Tumbleweed `openssh-server-9.6p1-11.2.x86_64.rpm` package, both with and without the above options.

Note that the 2fa method I am referring to here is the [Number Matching MFA](https://learn.microsoft.com/en-gb/entra/identity/authentication/how-to-mfa-number-match) method where the code is displayed on the device you're authenticating to, and you have to input that code into the Microsoft Authenticator App.
The standard TOTP MFA method where-by the code generated in the app is entered into the authentication prompt after you enter your password works completely and entirely as expected.

Enabling verbose logging on the ssh client when attempting to authenticate confirms that the Authentication Methods that is being attempted is `keyboard-interactive`.

**Comment by dmulder** [comment]
Hrm, I thought I had tested this, but maybe I missed it.
Maybe we could work around this by requiring input from the number matching MFA?

**Comment by deejay-ursys** [comment]
After testing further, I can confirm that the Number Matching code does currently show up if the OpenSSH server you are connecting to is running Ubuntu 24.04 LTS.

If the [previously mentioned OpenSSH Bug](https://bugzilla.mindrot.org/show_bug.cgi?id=2876) is the cause of this issue, then [this](https://git.launchpad.net/ubuntu/+source/openssh/commit/?id=fbc875e643e38b0f3a31537488a1ab3adc5e0819) out-of-tree patch by the Ubuntu maintainers for the Ubuntu 24.04 LTS `openssh-server` package (which is a port of [this](https://github.com/openssh/openssh-portable/pull/452) upstream pending patch on the `openssh-portable` project) is likely the reason that it does work on Ubuntu 24.04 LTS.

I don't know that the implications of this are in regard to this project and this issue, or if there are other distros that also apply this patch out-of-tree.
The solution may be to close this issue as unsupported and try to push for the upstream patch to be applied.

**Comment by dmulder** [comment]
I've filed a TW bug: https://bugzilla.opensuse.org/show_bug.cgi?id=1229010

**Comment by dmulder** [comment]
FYI, I've added a temporary patch to work around this issue in the next version of Himmelblau (which is being merged into the Samba tree): https://gitlab.com/samba-team/samba/-/merge_requests/3670/diffs?commit_id=fdd377f6f2ba2dc577e94d874771ff27deef9012

**Comment by deejay-ursys** [comment]
Is it possible for this workaround patch to be togglable via config in case we're using OpenSSH with the previously mentioned patch (whether that's by running Ubuntu 24.04, any other distro that may adopt the patch, or by running a custom-patched OpenSSH binary)

**Comment by dmulder** [comment]
Yes, I could do that.

**Comment by dmulder** [comment]
I've added the pam option "mfa_poll_prompt". You'll need to add this option to the pam config line for pam_auth when this work around is required.

**Comment by dmulder** [comment]
FYI, this workaround is no longer necessary in openSUSE Tumbleweed. The OpenSSH bug has been patched.

**Comment by dmulder** [comment]
@deejay-ursys see the following write up explaining the problem, and how to work around it: https://github.com/himmelblau-idm/himmelblau/wiki/OpenSSH-Bug-2876-%E2%80%90--Unable-to-use-MFA-over-SSH-%E2%80%90-Workaround
