### ISSUE TITLE
RHEL/Rocky Linux 8.x "id" command lookups are broken

### ISSUE THREAD

**Issue by tastle73** [himmelblau-idm/himmelblau#171]
I compiled HB pretty easily and attached it to AAD. 
I can log in as an Entra/AAD user but the nsswitch UID to plain name resolution is broken.

/usr/bin/id: cannot find name for user ID 5087
/usr/bin/id: cannot find name for group ID 5087
/usr/bin/id: cannot find name for user ID 5087

getent passwd:

tss:x:59:59:Account used for TPM access:/dev/null:/sbin/nologin
sshd:x:74:74:Privilege-separated SSH:/var/empty/sshd:/sbin/nologin
unbound:x:998:995:Unbound DNS resolver:/etc/unbound:/sbin/nologin
tom@pcc.com:x:5087:5087:Tom Astle:/home/tom@pcc.com:/bin/bash

nsswitch.conf:
passwd:      compat systemd himmelblau
shadow:     compat systemd himmelblau
group:        compat systemd himmelblau

sssd is disabled.

**Comment by dmulder** [comment]
I just ran a quick test and this works on openSUSE Tumbleweed. I'll test it on Rocky 8.

**Comment by dmulder** [comment]
Quick question @tastle73, did you disable nscd?

**Comment by dmulder** [comment]
@tastle73 would you mind sharing the dependencies to build on Rocky 8?

**Comment by dmulder** [comment]
Get me debug output from the daemon when the id command fails, and I can try to track down what issue you're encountering.

**Comment by tastle73** [comment]
> Quick question @tastle73, did you disable nscd?

yes

**Comment by tastle73** [comment]
> @tastle73 would you mind sharing the dependencies to build on Rocky 8?

00000000-0000-0000-0000-000000000000 DEBUG    🐛 [debug]: reuse idle connection for ("https", login.microsoftonline.com)
00000000-0000-0000-0000-000000000000 DEBUG    🐛 [debug]: pooling idle connection for ("https", login.microsoftonline.com)
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Authentication successful for user 'tom@pcc.com'
00000000-0000-0000-0000-000000000000 DEBUG    🐛 [debug]: resolving host="graph.microsoft.com"
00000000-0000-0000-0000-000000000000 DEBUG    🐛 [debug]: connecting to 20.190.161.25:443
00000000-0000-0000-0000-000000000000 DEBUG    🐛 [debug]: connected to 20.190.161.25:443
00000000-0000-0000-0000-000000000000 DEBUG    🐛 [debug]: insert -> 1
tom@pcc.com:x:5087:5087:Tom Astle:/home/tom@pcc.com:/bin/bash
00000000-0000-0000-0000-000000000000 DEBUG    🐛 [debug]: insert -> 1
00000000-0000-0000-0000-000000000000 DEBUG    🐛 [debug]: insert -> 1
00000000-0000-0000-0000-000000000000 DEBUG    🐛 [debug]: insert -> 1
00000000-0000-0000-0000-000000000000 DEBUG    🐛 [debug]: insert -> 1
00000000-0000-0000-0000-000000000000 DEBUG    🐛 [debug]: insert -> 1
00000000-0000-0000-0000-000000000000 DEBUG    🐛 [debug]: insert -> 1
00000000-0000-0000-0000-000000000000 DEBUG    🐛 [debug]: delete memberships -> 7
00000000-0000-0000-0000-000000000000 DEBUG    🐛 [debug]: insert membership -> 1
00000000-0000-0000-0000-000000000000 DEBUG    🐛 [debug]: insert membership -> 1
00000000-0000-0000-0000-000000000000 DEBUG    🐛 [debug]: insert membership -> 1
00000000-0000-0000-0000-000000000000 DEBUG    🐛 [debug]: insert membership -> 1
00000000-0000-0000-0000-000000000000 DEBUG    🐛 [debug]: insert membership -> 1
00000000-0000-0000-0000-000000000000 DEBUG    🐛 [debug]: insert membership -> 1
00000000-0000-0000-0000-000000000000 DEBUG    🐛 [debug]: insert membership -> 1
00000000-0000-0000-0000-000000000000 DEBUG    🐛 [debug]: token -> Some(UserToken { name: "tom@pcc.com", spn: "tom@pcc.com", uuid: 1802f9ff-1079-42d7-9897-f8656116ba35, gidnumber: 5087, displayname: "Tom Astle", shell: Some("/bin/bash"), groups: [GroupToken { name: "a0e26cfb-6a9a-4ee6-9ce5-114bf9c2bea4", spn: "a0e26cfb-6a9a-4ee6-9ce5-114bf9c2bea4", uuid: a0e26cfb-6a9a-4ee6-9ce5-114bf9c2bea4, gidnumber: 5181 }, GroupToken { name: "91201416-47c9-4f6a-bf69-b905402c18cc", spn: "91201416-47c9-4f6a-bf69-b905402c18cc", uuid: 91201416-47c9-4f6a-bf69-b905402c18cc, gidnumber: 5295 }, GroupToken { name: "f060f97f-566e-48ce-a1ef-17c7a6994960", spn: "f060f97f-566e-48ce-a1ef-17c7a6994960", uuid: f060f97f-566e-48ce-a1ef-17c7a6994960, gidnumber: 5172 }, GroupToken { name: "184e531b-54e0-4f4b-9960-e526c591ce16", spn: "184e531b-54e0-4f4b-9960-e526c591ce16", uuid: 184e531b-54e0-4f4b-9960-e526c591ce16, gidnumber: 5410 }, GroupToken { name: "ff87694c-c8f2-4d3b-9f69-d375ce6c9df7", spn: "ff87694c-c8f2-4d3b-9f69-d375ce6c9df7", uuid: ff87694c-c8f2-4d3b-9f69-d375ce6c9df7, gidnumber: 5827 }, GroupToken { name: "2c94ded3-b389-47cd-8fcf-c5542bb4bcf9", spn: "2c94ded3-b389-47cd-8fcf-c5542bb4bcf9", uuid: 2c94ded3-b389-47cd-8fcf-c5542bb4bcf9, gidnumber: 5144 }, GroupToken { name: "tom@pcc.com", spn: "tom@pcc.com", uuid: 1802f9ff-1079-42d7-9897-f8656116ba35, gidnumber: 5087 }], sshkeys: [], valid: true })
00000000-0000-0000-0000-000000000000 DEBUG    🐛 [debug]: flushed response!
00000000-0000-0000-0000-000000000000 DEBUG    🐛 [debug]: pooling idle connection for ("https", graph.microsoft.com)00000000-0000-0000-0000-000000000000 DEBUG    🐛 [debug]: Disconnecting client ...

**Comment by dmulder** [comment]
This just appears to show a successful getent. Where's the failing id command?

**Comment by tastle73** [comment]
It seems to be a permission issue.  If I run the id command as root, I get good output.  As  a regular user, it does not
