### ISSUE TITLE
Support for Ubuntu 20.04, 22.04, and 24.04

### ISSUE THREAD

**Issue by jkatzmaier2** [himmelblau-idm/himmelblau#180]
We would really like to use your Entra ID authentication project on Ubuntu Desktop. We're currently running 20.04 on our fleet of machines, and will eventually move them to 22.04 and then 24.04.

I tried compiling himmelblau main as of today on 20.04 with rustc 1.81.0 and it failed in openssl with the error: 

error: failed to run custom build command for `openssl-kdf v0.4.2`

Caused by:
  process didn't exit successfully: `/home/jkatzmaier/Downloads/tmp/himmelblau/target/debug/build/openssl-kdf-b82c3e2b748df494/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=OPENSSL_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=OPENSSL_STATIC
  cargo:rerun-if-env-changed=OPENSSL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=SYSROOT
  cargo:rerun-if-env-changed=OPENSSL_STATIC
  cargo:rerun-if-env-changed=OPENSSL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rustc-link-search=native=/usr/lib/x86_64-linux-gnu
  cargo:rustc-link-lib=ssl
  cargo:rustc-link-lib=crypto
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=OPENSSL_STATIC
  cargo:rerun-if-env-changed=OPENSSL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at /home/jkatzmaier/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-kdf-0.4.2/build.rs:68:9:
  No OpenSSL implementations available.
  Please use a version of OpenSSL that has the necessary patch backported, or
  use the `allow_custom` feature to allow the use of the custom implementation.

We would eventually like to build packages for 20.04, 22.04, and 24.04. Any assistance would be greatly appreciated.

**Comment by dmulder** [comment]
Looks like you need to install the `openssl3` system package. It looks like I neglected to add that to the dependency list! Sorry about that.

**Comment by jkatzmaier2** [comment]
Hi David,

It appears that openssl 3 is not available for Ubuntu 20.04, only for 22.04 and 24.04. The system package name in Ubuntu is openssl

Is openssl 3 just a build-time dependency or is it also a run-time dependency?



John Katzmaier

Sr. IT Infrastructure Engineer

Global Information Services

iRobot
8 Crosby Drive
Bedford, MA 01730
t: 781.430.3418
***@***.***



[signature_2105017320]



Follow us on social media:

Facebook<https://www.facebook.com/iRobot/> | Twitter<https://twitter.com/iRobot> | Instagram<https://www.instagram.com/irobot/> | YouTube<https://www.youtube.com/user/irobot>



________________________________

**Comment by dmulder** [comment]
> Hi David, It appears that openssl 3 is not available for Ubuntu 20.04, only for 22.04 and 24.04. The system package name in Ubuntu is openssl Is openssl 3 just a build-time dependency or is it also a run-time dependency?

It's a runtime dependency. openssl 1 doesn't have certain crypto algorithms that are necessary for communicating with Entra Id.

**Comment by jkatzmaier2** [comment]
Hi David,

In that case, we won't be using himmelblau due to requiring Ubuntu 20.04 support and that distribution version having an OpenSSL version that is too old. I will revisit it when we move our machines to Ubuntu 22.04. Thank you for the support!





John Katzmaier

Sr. IT Infrastructure Engineer

Global Information Services

iRobot
8 Crosby Drive
Bedford, MA 01730
t: 781.430.3418
***@***.***



[signature_2105017320]



Follow us on social media:

Facebook<https://www.facebook.com/iRobot/> | Twitter<https://twitter.com/iRobot> | Instagram<https://www.instagram.com/irobot/> | YouTube<https://www.youtube.com/user/irobot>



________________________________

**Comment by dmulder** [comment]
I'm sorry it won't work for you! Let me know if you need any assistance in the future.
