### ISSUE TITLE
Domain name in the himmelblaud.conf configuration file

### ISSUE THREAD

**Issue by run-stop** [himmelblau-idm/himmelblau#205]
Hello,

Today I discovered that using primary domain in the himmelblaud configuration file does not always work.

For example:
- Azure portal reports the primary domain as `example.onmicrosoft.com`
- We configure `domains = example.onmicrosoft.com` in the himmelblaud.conf
- `getent passwd user.name@example.com` does not complete sucesfully

When we change the domains parameter to `domains = example.com`, `getent` command will return the information about the user.

**Comment by dmulder** [comment]
This is now resolved. Only the primary domain need be listed in the `domains` option, and other custom domains will be detected automatically.
