### ISSUE TITLE
Build Rocky/EL rpms with `cargo rpm`

### ISSUE THREAD

**Issue by dmulder** [himmelblau-idm/himmelblau#206]
We should use `cargo rpm` to build rpms for various distributions, including Rocky (and compatible with RHEL, etc).

**Comment by tastle73** [comment]
this would be appreciated

**Comment by dmulder** [comment]
> this would be appreciated

Which distributions (and versions) specifically do you need packages for? I'll try to target these.

**Comment by tastle73** [comment]
rocky linux 8
