### ISSUE TITLE
SSH MFA timeout

### ISSUE THREAD

**Issue by aleksandarmiljkovic-tomtom** [himmelblau-idm/himmelblau#219]
There's a bug while using himmelblau with SSH and you let the password prompt expire:

Steps to reproduce:
- Once himmelblau is configured and installed, I'm running SSH to the host. 
- SSH prompt displays the PAM message. If you let the SSH password prompt timeout (which is triggered by the SSHD), 
- himmelblaud will still wait for MFA token and pool Azure indefinitely.

Expired SSH login session should somehow trigger himmelblaud to stop pooling Azure API.

**Comment by dmulder** [comment]
The pooling issue is with the DAG prompt. In addition to this, the are instances when we send a DAG, when we should actually fail. For example, we should send a DAG on an invalid password, and we shouldn't send a DAG when the failure was due to an invalid username.
