### ISSUE TITLE
Improvement Suggestion: Adding openssh-server as dependency for himmelblau DEB package

### ISSUE THREAD

**Issue by aleksandarmiljkovic-tomtom** [himmelblau-idm/himmelblau#227]
Ubuntu Desktop OS does not include OpenSSH by default. The administrator needs to install the SSH package manually. When installing the himmelblau DEB package, we change the _KbdInteractiveAuthentication_ option from "no" to "yes" to enable the MFA prompt for SSH. This will not work without OpenSSH installed.

Suggestion:

Update the Cargo.toml [package.metadata.deb] section to include:
```toml
pre-depends = "openssh-server"
```
As documented [here](https://www.debian.org/doc/debian-policy/ch-relationships.html#binary-dependencies-depends-recommends-suggests-enhances-pre-depends), pre-depends ensures that openssh-server is installed and configured before installing himmelblau.

**Comment by dmulder** [comment]
Ah, good catch. Do we really want to force installers to install ssh though? Perhaps we can have it as a suggestion, then not install the `KbdInteractiveAuthentication` option if ssh isn't present?
