### ISSUE TITLE
Ubuntu Bug: Symlinked home folders do not work on Ubuntu

### ISSUE THREAD

**Issue by aleksandarmiljkovic-tomtom** [himmelblau-idm/himmelblau#228]
In it's current state, himmelblau creates two folders in the /home folder:
- /home/<UID> => the real directory hosting user's home
- /home/username@domain.com -> /home/<UID> => symlink to the original home directory

On Ubuntu this does not work for any of it's snap applications, docker containers, etc.

To fix this:
- I had to remove the symlink from `/home/username@domain.com`
- Create a directory with the same name `/home/username@domain.com`
- Bind-mount as follows: `mount --bind /home/<uid> /home/username@domain.com`

Once this is done, everything works as expected.

Would it be possible to modify code to actually use bind-mount instead of symlink?

**Comment by dmulder** [comment]
There is an easy work around that I just realized. Set these two parameters in your himmelblau.conf:
```ini
home_attr = SPN
home_alias = SPN
```
This effectively disables the home dir aliasing.

**Comment by run-stop** [comment]
I can confirm this is working in `[global]` section. If you set parameters under the domain section at the bottom of the config file, parameters are ignored.
