### ISSUE TITLE
Implement passwordless

### ISSUE THREAD

**Issue by dmulder** [himmelblau-idm/himmelblau#229]
I know how to implement passwordless, but it will require 3 interactions rather than the previous 2 in libhimmelblau.

**Comment by Appiejs** [comment]
Can you describe how you managed to do this without a password login?

**Comment by dmulder** [comment]
It's fairly straight forward.
You get a MS Authenticator entropy when you send a GetCredentialType request, but only if you specify `isRemoteNGCSupported = true` in the request. Then you authenticate the user via the Authenticator app when they supply the entropy.

**Comment by dmulder** [comment]
Probably within a month it will be in main.

**Comment by dmulder** [comment]
Released here: https://github.com/himmelblau-idm/himmelblau/releases/tag/0.8.0

Merry Christmas!

**Comment by Appiejs** [comment]
Cool Will have a look.Is there a manual on how to update  and use?Op 19 dec 2024 om 23:53 heeft David Mulder ***@***.***> het volgende geschreven:﻿
Released here: https://github.com/himmelblau-idm/himmelblau/releases/tag/0.8.0
Merry Christmas!

**Comment by dmulder** [comment]
> Cool Will have a look.Is there a manual on how to update  and use?

https://github.com/himmelblau-idm/himmelblau/wiki

Also, there are man packages included in the packages.

If you're just updating from a previously configured version of Himmelblau, just install the new packages. Passwordless auth is enabled by default (if configured for the user).

See the following for configuration passwordless auth (per-user configuration):

https://learn.microsoft.com/en-us/entra/identity/authentication/howto-authentication-passwordless-phone

**Comment by Appiejs** [comment]
Thanks, could upgrade and followed the steps.
Only receiving the following error when try to connect:
Dec 20 18:30:34 himmelblau sshd[603]: PAM unable to dlopen(/lib64/security/pam_himmelblau.so): /lib64/security/pam_himmelblau.so: cannot open shared object file: No such file or directory
Dec 20 18:30:34 himmelblau sshd[603]: PAM adding faulty module: /lib64/security/pam_himmelblau.so
Dec 20 18:30:34 himmelblau sshd[603]: error: PAM: Authentication failure for userXXXX

Any idea what it could be?

**Comment by Appiejs** [comment]
> Thanks, could upgrade and followed the steps. Only receiving the following error when try to connect: Dec 20 18:30:34 himmelblau sshd[603]: PAM unable to dlopen(/lib64/security/pam_himmelblau.so): /lib64/security/pam_himmelblau.so: cannot open shared object file: No such file or directory Dec 20 18:30:34 himmelblau sshd[603]: PAM adding faulty module: /lib64/security/pam_himmelblau.so Dec 20 18:30:34 himmelblau sshd[603]: error: PAM: Authentication failure for userXXXX
> 
> Any idea what it could be?

Never mind, i reinstall on a new machine and all is working.
