### ISSUE TITLE
make install is not working on Ubuntu

### ISSUE THREAD

**Issue by barkermn01** [himmelblau-idm/himmelblau#251]
So i have managed to get everything setup and installed, and even used `pam-auth-update` to update the PAM Config's and it appears to work SSH into server it's asking for username password via KeyboardInteraction, however it errors with `Access denied` upon checking the `/var/log/auth.log` file
```
2024-10-15T11:17:01.332830+00:00 ip-10-1-1-61 CRON[10654]: PAM unable to dlopen(pam_himmelblau.so): /usr/lib/security/pam_himmelblau.so: cannot open shared object file: No such file or directory
2024-10-15T11:17:01.332982+00:00 ip-10-1-1-61 CRON[10654]: PAM adding faulty module: pam_himmelblau.so
2024-10-15T11:17:01.335665+00:00 ip-10-1-1-61 CRON[10654]: pam_unix(cron:session): session opened for user root(uid=0) by root(uid=0)
2024-10-15T11:17:01.339800+00:00 ip-10-1-1-61 CRON[10654]: pam_unix(cron:session): session closed for user root
```

So I think the `make install` is not putting one of the files in the correct place.

**Comment by barkermn01** [comment]
This seems to be confirmed because i get asked for password twice after copying `/target/release/libpam_himmelblau.so` to `/usr/lib/security/` to do this i had to create that directory so as root i ran the following where `{source_dir}` is the directory of the source code clone.

```sh
mkdir /usr/lib/security
chmod 755 /usr/lib/security
cp {source_dir}/target/release/libpam_himmelblau.so /usr/lib/security/pam_himmelblau.so
```

**Comment by dmulder** [comment]
Well that's strange, because I'm also testing on 24.04, and it's expecting the pam module in `/usr/lib/x86_64-linux-gnu/security`.

**Comment by dmulder** [comment]
Also @barkermn01, have you tried the Ubuntu packages? They're attached to the release: https://github.com/himmelblau-idm/himmelblau/releases/tag/0.6.13

**Comment by barkermn01** [comment]
I have not yet, it is going to be my plan, I just rebuilt my instance this morning, after bricking my login after last time I was attempting this, I will be looking at the PPA version soon, but then this feedback might be needed for the PPA.

**Comment by dmulder** [comment]
@run-stop was working on a ppa, but I'm not sure whether he has it working or not.

**Comment by dmulder** [comment]
@barkermn01 also keep in mind the Ubuntu configuration note added to the wiki: https://github.com/himmelblau-idm/himmelblau/wiki#configuring-himmelblau

Snaps fail to execute if you don't configure the himmelblau.conf as explained.
