### ISSUE TITLE
Improvement suggestion: ability to define a default login domain in config

### ISSUE THREAD

**Issue by Nidhoggrr** [himmelblau-idm/himmelblau#263]
Especially for long domain names, it would be convenient, to be able to define a default login domain.

So users could login with username (left part from @) instead of username@domain.com.

**Comment by dmulder** [comment]
In 0.6.x, this is already possible. In your himmelblau.conf, the first domain in the the `domains` list is the default, and users can login using the short part of their name (the CN).

**Comment by dmulder** [comment]
See #231, this behavior is enabled by default.
