### ISSUE TITLE
Improvement Suggestion: Automating Local Configuration for Entra ID Users on First Login

### ISSUE THREAD

**Issue by run-stop** [himmelblau-idm/himmelblau#265]
**Problem description**
When enabling Himmelblau, Entra ID users do not exist on the system initially. After logging in with the new user account, I've created an Entra ID group and configured appropriate `sudo` permissions, allowing the user to run `sudo` commands. This works fine for the CLI; however, it doesn't apply to UI applications. Gnome still prompts for the local administrator’s password, even though the user is permitted to use `sudo`.

**Solution**
To resolve this, the user must be added to the local `sudo` group (at least on Ubuntu). Once added, Entra ID users will be prompted for their own credentials within Gnome. The challenge is that I can only "see" the user after they've logged into the system, making it difficult to automate this process.

**Proposal:**
I suggest implementing a "first-time login" facility that triggers a system administrator-provided script when the user logs in for the first time. The script could receive the user's identity (perhaps through an environment variable) and handle the necessary local configuration, such as adding the user to the `sudo` group.

**Comment by dmulder** [comment]
#271 is related to this.

**Comment by dmulder** [comment]
In addition, there should be a way to specify a script which will be run at first login, as well as a script for every login. These can be used for initial setup, as well as for compliance checks. At some point we could integrate the `every login` script to mark the device as MDM compliant.
