### ISSUE TITLE
rpm installation fails on rocky9

### ISSUE THREAD

**Issue by Nidhoggrr** [himmelblau-idm/himmelblau#280]
Hi,

the installation of the packet fails on rocky9:
```bash
$ LANG=C sudo dnf install himmelblau-0.7.0-1.x86_64-rocky9.rpm 
Last metadata expiration check: 1:15:58 ago on Fri Nov  8 15:49:24 2024.
Error: 
 Problem: conflicting requests
  - nothing provides sqlite3 needed by himmelblau-0.7.0-1.x86_64 from @commandline
  - nothing provides openssl-3 needed by himmelblau-0.7.0-1.x86_64 from @commandline
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

as the packages are named differently in the `Cargo.toml` at least for rocky9
I was able to build installable packages with these changes:
```
--- a/src/daemon/Cargo.toml
+++ b/src/daemon/Cargo.toml
@@ -51,8 +51,8 @@ recommends = ["nss-himmelblau", "pam-himmelblau"]
 assets = [
   ["../../platform/debian/himmelblau.conf.example", "etc/himmelblau/himmelblau.conf", "644"],
   ["target/release/aad-tool", "usr/bin/", "755"],
-  ["../../platform/debian/himmelblaud-tasks.service", "etc/systemd/system/", "644"],
-  ["../../platform/debian/himmelblaud.service", "etc/systemd/system/", "644"],
+  ["../../platform/debian/himmelblaud-tasks.service", "etc/systemd/system/himmelblaud-tasks.service", "644"],
+  ["../../platform/debian/himmelblaud.service", "etc/systemd/system/himmelblaud.service", "644"],
   ["../../platform/debian/org.samba.himmelblau.conf", "usr/share/dbus-1/system.d/", "644"],
   ["../../platform/debian/com.microsoft.identity.broker1.service", "usr/share/dbus-1/services/", "644"],
   @@ -78,8 +78,8 @@ assets = [
 ]
 
 [package.metadata.generate-rpm.requires]
-openssl-3 = "*"
-sqlite3 = "*"
+openssl = "*"
+sqlite = "*"
 
 [package.metadata.generate-rpm.recommends]
 nss-himmelblau = "*"
 
 ```
 
 
 The installation of `sshd_config` fails still:
 ```bash
 $ LANG=C sudo dnf install himmelblau-sshd-config-0.7.0-1.x86_64.rpm 
Last metadata expiration check: 1:20:32 ago on Fri Nov  8 15:49:24 2024.
Error: 
 Problem: conflicting requests
  - nothing provides  needed by himmelblau-sshd-config-0.7.0-1.x86_64 from @commandline
 ```
 
 even though i fixed `sshd` vs `openssh-server`dependency:
 ```
diff --git a/src/sshd-config/Cargo.toml b/src/sshd-config/Cargo.toml
index 31cdfe7..f49c0db 100644
--- a/src/sshd-config/Cargo.toml
+++ b/src/sshd-config/Cargo.toml
@@ -26,4 +26,4 @@ assets = [
 ]
 
 [package.metadata.generate-rpm.requires]
-sshd = "*"
+openssh-server = "*"

```

**Comment by dmulder** [comment]
Yes, I actually discovered these as well last night. I was planning to backport the fix today.

**Comment by dmulder** [comment]
Also, I'll give you a heads up. We have a Rocky 8 build, but you have to manually build and install the utf8proc dependency yourself for now (none of the major distros are shipping this dependency). I am planning to package it and provide it here to make installation easier.

**Comment by dmulder** [comment]
@Nidhoggrr see the latest release with these issues resolved: https://github.com/himmelblau-idm/himmelblau/releases/tag/0.7.1

Let me know if you encounter any other problems!

**Comment by dmulder** [comment]
> The installation of `sshd_config` fails still:
> 
> ```shell
> $ LANG=C sudo dnf install himmelblau-sshd-config-0.7.0-1.x86_64.rpm 
> Last metadata expiration check: 1:20:32 ago on Fri Nov  8 15:49:24 2024.
> Error: 
> Problem: conflicting requests
>  - nothing provides  needed by himmelblau-sshd-config-0.7.0-1.x86_64 from @commandline
> ```
> 
> even though i fixed `sshd` vs `openssh-server`dependency:
> 
> ```
> diff --git a/src/sshd-config/Cargo.toml b/src/sshd-config/Cargo.toml
> index 31cdfe7..f49c0db 100644
> --- a/src/sshd-config/Cargo.toml
> +++ b/src/sshd-config/Cargo.toml
> @@ -26,4 +26,4 @@ assets = [
> ]
> 
> [package.metadata.generate-rpm.requires]
> -sshd = "*"
> +openssh-server = "*"
> ```

Oh, I missed this comment. It sounds like there is still some issue with the sshd_config package then. I'll need to look into this.

**Comment by dmulder** [comment]
I just installed 0.7.1 on a rocky9 container and I didn't encounter any errors this time. Could you check if those issues are resolved for you as well @Nidhoggrr?

**Comment by Nidhoggrr** [comment]
Wow, you are so quick, I highly appreciate it :)

Indeed the error is gone for `himmelblau-sshd-config-0.7.1-1.x86_64.rpm`

thank you! =b

**Comment by dmulder** [comment]
@Nidhoggrr hang on a moment though. I just discovered another packaging bug! Sorry. I'll need to spin a 0.7.2 here in a bit.

**Comment by dmulder** [comment]
The latest bug allows himmelblau to install, but you wont be able to authenticate.

**Comment by dmulder** [comment]
> The latest bug allows himmelblau to install, but you wont be able to authenticate.

Scratch that, the bug only effects Rocky8 and openSUSE Tumbleweed. Rocky9 should be good to go for testing in 0.7.1.
