### ISSUE TITLE
missing dependency utf8proc_NFKC_Casefold Rocky 8

### ISSUE THREAD

**Issue by tastle73** [himmelblau-idm/himmelblau#296]
**Description**
systemctl started himmelblaud.  It failed silently.  Found this in syslog:  symbol lookup error: /usr/sbin/himmelblaud: undefined symbol: utf8proc_NFKC_Casefold

**Steps to Reproduce**
1. systemctl start himmelblaud

**Logs and Output**

Nov 15 15:42:00 rj systemd[1]: Started Himmelblau Authentication Daemon.
Nov 15 15:42:00 rj himmelblaud[1480534]: /usr/sbin/himmelblaud: symbol lookup error: /usr/sbin/himmelblaud: undefined symbol: utf8proc_NFKC_Casefold
Nov 15 15:42:00 rj systemd[1]: himmelblaud.service: Main process exited, code=exited, status=127/n/a
Nov 15 15:42:00 rj systemd[1]: himmelblaud.service: Failed with result 'exit-code'.

**Environment**
- **Linux Distro**:  Rocky 8
- **Package source (distro package/github release/self built)**:  distro RPM
- **Himmelblau Version**: 0.7.2

**Comment by dmulder** [comment]
Sorry, I meant to leave a note about this. Rocky/RHEL 8 does not provide utf8proc, AFAIK. You have to build and install it yourself for now. Packaging utf8proc is one of the things on my todo list.

**Comment by dmulder** [comment]
Also, FYI, you have to disable Hello auth on Rocky 8, since it doesn't support openssl 3.

**Comment by dmulder** [comment]
Here are instructions for installing utf8proc:
```sh
wget https://github.com/JuliaStrings/utf8proc/archive/refs/tags/v2.6.1.tar.gz -O utf8proc-2.6.1.tar.gz
mkdir -p utf8proc-rocky8
tar -xvf utf8proc-$VERSION.tar.gz -C utf8proc-rocky8 --strip-components=1
cd utf8proc-rocky8
make && sudo make install
```

**Comment by tastle73** [comment]
There is actually a(n) utf8proc RPM.  It doesn't seem to have the right symbols in it though?

**Comment by dmulder** [comment]
> There is actually a(n) utf8proc RPM. It doesn't seem to have the right symbols in it though?

Hrm, what version is it?

**Comment by tastle73** [comment]
2.6.1-3.module+el8.7.0+1065+42200b2e

**Comment by dmulder** [comment]
> 2.6.1-3.module+el8.7.0+1065+42200b2e

Well that's strange. That's the same version I'm building with. I recall now that the issue I had was that el8 doesn't package the utf8proc devel package, so I'm unable to build against it (no header files, etc). So I fetch the tar and build it myself for that reason.

I'll have to test this myself and see if I can track down the cause.

**Comment by tastle73** [comment]
I "sort of" figured this out. There is something about the RPM version that is different than the manually compiled one you had me do. The manually built and installed one works, but then I have to "nodeps" install the himmelblau package. 

You mentioned there not being a -devel package in RL, but there is actually.

**Comment by dmulder** [comment]
What repo do you find the devel package in? I wasn't able to find it.

**Comment by dmulder** [comment]
I think there is a bug in yum. I can see the packages here:
http://downloads.rockylinux.org/pub/rocky/8.10/PowerTools/x86_64/os/Packages/u/

If I add this repo and update, yum doesn't see them. I can enable devel packages, and then I see an old version of utf8proc-devel, but I can't install it because utf8proc is newer.

**Comment by dmulder** [comment]
AH, it's filtered out by a module. Sorry, I'm very unfamiliar with EL distros.
https://github.com/himmelblau-idm/himmelblau/pull/303
https://github.com/himmelblau-idm/himmelblau/pull/304
