### ISSUE TITLE
Repeating error complaining about tenant_id

### ISSUE THREAD

**Issue by tastle73** [himmelblau-idm/himmelblau#298]
**Description**
this error repeats over and over again in syslog:

Nov 19 12:18:22 rj himmelblaud[1627476]: 00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: json error -> Error("missing field `tenant_id`", line: 1, column: 617)

version= 0.7.2
OS = RockyLinux 8.10

**Comment by dmulder** [comment]
Interesting. I think that's federation provider request that's failing, which suggests that MS isn't responding with the tenant id in the usual way. There is another way to make that request though. Would you mind privately sharing your himmelblau.conf so I can debug? (that is an un-authenticated request, so I can reproduce it here)

**Comment by tastle73** [comment]
how do I do that?

**Comment by dmulder** [comment]
> how do I do that?

You could share it either via email <dmulder@samba.org> or via Matrix https://matrix.to/#/#himmelblau:matrix.org

**Comment by dmulder** [comment]
Ok, I just checked and the federation provider request is responding with the tenant id as expected. This error is coming from somewhere else.

Is it causing a fatal failure? Does himmelblaud stop? Are you able to authenticate, etc? I'm just trying to track down which call is expecting that tenant_id parameter.

**Comment by tastle73** [comment]
Yes, that worked.

**Comment by dmulder** [comment]
Awesome.
