### ISSUE TITLE
Multi Domain support not working 

### ISSUE THREAD

**Issue by goldfinger3** [himmelblau-idm/himmelblau#314]
****
Multi Domain/UPN support not working, Himmelblau daemon can't start

**Environment**
We have serveral verfied domains in this tenant.  
https://learn.microsoft.com/en-us/entra/identity/users/domains-manage

Example:
Primary domain: test.onmicrosoft.com
Verified domain: mydomain.net

As a result, there are users with different UPNs.  

**Steps to Reproduce**
1.  As expected, users with the same UPN as the primary domain work
       **domains = test.onmicrosoft.com**
       user<nolink>@test.onmicrosoft.com --> himmelblau works

2.   In the next step we added the verified domain name to the domain settings in himmelblau.conf. 
        Comma-separated list with two domains
        **domains = test.onmicrosoft.com,mydomain.net**
     
     After a reboot or restart of the services, the himmelblau daemon no longer works.

**Error**
suse15:/home/azureadmin # aad-tool status
2024-12-06T16:10:49.234103Z ERROR aad_tool: himmelblaud socket /var/run/himmelblaud/socket does not exist - is the service running?

**Used Version**
0.7.7+git.0.b48d0bb-lp156.43.1 on openSUSE Leap 15.6
0.7.9+git.0.93655d2-lp156.46.1 on openSUSE Leap 15.6

**Comment by dmulder** [comment]
I'll take a look at it today.

**Comment by dmulder** [comment]
Also, when you change the idmapping, you SHOULD run `sudo aad-tool cache-clear --really`, otherwise you again run the potential of overlapping uid's (because the cache contains the old idmapping).

**Comment by goldfinger3** [comment]
I tried it today, butit till didn't work.  Maybe we have to reopen this issue
I used a clean snapshot again for the installation. I also deleted the azure-joined device in the Entra ID. 
As before, the daemon does not start with two or more domain entries. Although I have added a separate, non-overlapping idmap_range for each registered domain.  There is also no idmap range of a domain not listed in domains.
But I still get an IdmapError(0xb).
With only one domain including its  idmap range in the configuration file, the daemon works for all respective domains.

Is there a way to get more infos about the IdmapError?

**journal log**
Dec 12 18:31:08 suse15 systemd[1]: /usr/lib/systemd/system/himmelblaud.service:11: CacheDirectory= path is absolute, ignoring: /var/cache/himmelblaud
Dec 12 18:31:08 suse15 systemd[1]: /usr/lib/systemd/system/himmelblaud.service:12: RuntimeDirectory= path is absolute, ignoring: /run/himmelblaud
Dec 12 18:31:08 suse15 systemd[1]: /usr/lib/systemd/system/himmelblaud.service:13: StateDirectory= path is absolute, ignoring: /var/lib/himmelblaud
Dec 12 18:31:17 suse15 systemd[1]: Started Himmelblau Authentication Daemon.
Dec 12 18:31:17 suse15 systemd[1]: Started Himmelblau Local Tasks.
Dec 12 18:31:17 suse15 himmelblaud_tasks[4572]: 00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Server started ...
Dec 12 18:31:17 suse15 himmelblaud_tasks[4572]: 00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Attempting to connect to himmelblaud ...
Dec 12 18:31:17 suse15 himmelblaud_tasks[4572]: 00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Unable to find himmelblaud, sleeping ...
Dec 12 18:31:22 suse15 himmelblaud_tasks[4572]: 00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Attempting to connect to himmelblaud ...
Dec 12 18:31:22 suse15 himmelblaud_tasks[4572]: 00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Unable to find himmelblaud, sleeping ...
Dec 12 18:31:24 suse15 himmelblaud[4571]: 00000000-0000-0000-0000-000000000000 WARN     🚧 [warn]: WARNING: DB folder /var/cache/himmelblaud has 'everyone' permission bits in the mo>
Dec 12 18:31:24 suse15 himmelblaud[4571]: 00000000-0000-0000-0000-000000000000 WARN     🚧 [warn]: hsm_type not configured, using default ...
Dec 12 18:31:25 suse15 himmelblaud[4571]: 00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: **IdmapError(0xb)**
Dec 12 18:31:25 suse15 systemd[1]: himmelblaud.service: Main process exited, code=exited, status=1/FAILURE
Dec 12 18:31:25 suse15 systemd[1]: himmelblaud.service: Failed with result 'exit-code'.
Dec 12 18:31:25 suse15 systemd[1]: himmelblaud.service: Consumed 7.738s CPU time.

sudo zypper search -s himmelblau
2024-12-12T17:22:24.520924Z ERROR Unix socket stream setup error while connecting to /var/run/himmelblaud/socket -> Os { code: 2, kind: NotFound, message: "No such file or directory" }
2024-12-12T17:22:24.520994Z ERROR Error DaemonClientBlocking::new() err=Os { code: 2, kind: NotFound, message: "No such file or directory" }
Loading repository data...
Reading installed packages...

S  | Name                   | Type       | Version                         | Arch   | Repository
---+------------------------+------------+---------------------------------+--------+-----------------------------------------
i+ | himmelblau             | package    | 0.7.13+git.0.d790d31-lp156.47.1 | x86_64 | Identity Management related tools (15.6)
   | himmelblau             | srcpackage | 0.7.13+git.0.d790d31-lp156.47.1 | noarch | Identity Management related tools (15.6)
   | himmelblau-sshd-config | package    | 0.7.13+git.0.d790d31-lp156.47.1 | noarch | Identity Management related tools (15.6)
i+ | libnss_himmelblau2     | package    | 0.7.13+git.0.d790d31-lp156.47.1 | x86_64 | Identity Management related tools (15.6)
i+ | pam-himmelblau         | package    | 0.7.13+git.0.d790d31-lp156.47.1 | x86_64 | Identity Management related tools (15.6)

**Comment by dmulder** [comment]
IdmapError(0xb) is an IDMAP_COLLISION, which means it thinks your idmap ranges are overlapping for some reason.

Can I get a copy of your himmelblau.conf? This error happens long before any auth attempt, etc, so with a copy of your himmelblau.conf I should be able to reproduce the behavior.
