### ISSUE TITLE
Package version doesn't match latest release

### ISSUE THREAD

**Issue by moritzheiber** [himmelblau-idm/himmelblau#53]
Hey, I'm considering packaging Himmelblau using `cargo-dist` or `cargo-deb` (or something similar) for Ubuntu LTS systems. I noticed that the version in `Cargo.toml` (currently at `0.1.0`) doesn't match the latest release (`0.1.1`) that's published on GitHub. Is that intended?

I learned that it's best practice to have the version in `Cargo.toml` point to the "next" release instead of the current one. In this instance, it's lacking behind one patch release and the supposed "next" patch release (i.e. my expectation would be for it to be bumped to `0.1.2`), which also makes packaging a little more difficult.

**Comment by dmulder** [comment]
Sorry about that. The current version is in branch stable-0.1.x, which I have not updated to match the Cargo.toml either. I'll fix that branch and the main branch today.

**Comment by dmulder** [comment]
Fixed.

**Comment by dmulder** [comment]
FYI, this project is currently packaged in openSUSE Tumbleweed, if you're interested: https://software.opensuse.org/package/himmelblau

**Comment by moritzheiber** [comment]
Thanks! I’ll take a look
